query ListProducts @auth(level: PUBLIC) {
  products(orderBy: { createdAt: DESC }) {
    id
    sku
    name
    category
    emoji
    image
    price
    cost
    stock
    compat
    status
    createdAt
    updatedAt
  }
}

query ListOrders @auth(level: USER) {
  orders(orderBy: { createdAt: DESC }) {
    id
    customer
    items
    total
    payment
    status
    time
    createdAt
    createdBy
  }
}

query GetUser($id: String!) @auth(level: USER) {
  user(id: $id) {
    id
    email
    role
    displayName
    photoURL
    createdAt
  }
}

query ListUsers @auth(level: USER) {
  users(orderBy: { createdAt: DESC }) {
    id
    email
    role
    displayName
    photoURL
    createdAt
  }
}
