type User @table {
  id: String! @col(name: "uid")
  email: String!
  role: String!
  displayName: String
  photoURL: String
  createdAt: Date!
}

type Product @table {
  id: String!
  sku: String!
  name: String!
  category: String!
  emoji: String
  image: String
  price: Float!
  cost: Float!
  stock: Int!
  compat: String
  status: String!
  createdAt: Date!
  updatedAt: Date!
}

type Order @table {
  id: String!
  customer: String!
  items: String!
  total: Float!
  payment: String!
  status: String!
  time: String
  createdAt: Date!
  createdBy: String
}
